test: &test
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: myapp
  password: password

development: &development
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: myapp
  password: password
<<<<<<< HEAD
=======

cucumber:
  <<: *test
>>>>>>> f1cfb7cf07bae1b2cd1dbe18d2090ff052499f07
